service: question-service-serverless
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  environment:
    GRAPHQL_ENDPOINT: ${env:GRAPHQL_ENDPOINT}
    GRAPHQL_QUERY: ${env:GRAPHQL_QUERY}
    MONGO_URI: ${env:MONGO_URI}


functions:
  updateQuestionDatabase:
    handler: src/handler.updateQuestionDatabase
    events:
      - schedule: rate(24 hours)

package:
  individually: true

